config/routes.rb
Ticketee::Application.routes.draw do
  
  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  get '/awaiting_confirmation',
    to: "users#confirmation",
    as: 'confirm_user'

  put '/admin/users/:user_id/permissions',
    to: 'admin/permissions#update',
    as: :update_user_permissions

  resources :files

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions      
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root to: 'projects#index'

end

app/views/notifier/comment_updated.html.erb
== ADD YOUR REPLY ABOVE THIS LINE ==

<img src='http://ticketeeapp.com/images.logo.png' alt='Ticketee' />

<p>
  Hello!
</p>

<p>
<%= @comment.user %> has just updated the <%= @comment.ticket.title %> ticket
for <%= @comment.ticket.project.name %>. They wrote:
</p>

<blockquote> <%= @comment.text %></blockquote>

<p>
You can 
<%= link_to "view this ticket online here", project_ticket_url(@comment.ticket.project, @comment.ticket) %>
</p>

app/views/notifier/comment_updated.text.erb
== ADD YOUR REPLY ABOVE THIS LINE ==

Hello!

<%= @comment.user %> has just updated the <%= @comment.ticket.title %> ticket
for <%= @comment.ticket.project.name %>. They wrote:

<%= @comment.text %>

You can view this ticket online by going to:
<%= project_ticket_url(@comment.ticket.project, @comment.ticket) %>